### ISSUE TITLE
Add Copying to G1, G2, GT

### ISSUE THREAD

**Issue by ValarDragon** [dis2/bls12#1]
Since the operations in this library are mutative, could a method to copy elements in each group be added?

Otherwise to copy points upstream, one has to Marshal and Unmarshal upstream to copy an element, which is unnecessarily costly.

**Comment by dis2** [comment]
You can always make copy simply by assignment, a lot of effort went into coaxing relic to allow us to hold their structs with no pointers. Copy() method still sounds fair though, as it allows for easier call chaining.

**Comment by dis2** [comment]
This oughta do it. https://github.com/dis2/bls12/commit/febae290b4510e86583fa937508deffa15c13002

**Comment by ValarDragon** [comment]
Thanks for implementing this! I hadn't realized that you were holding the relic structs without pointers!
