### ISSUE TITLE
Error occurs in Ubuntu 

### ISSUE THREAD

**Issue by CFHH** [dis2/bls12#6]
# github.com/dis2/bls12
/usr/bin/x86_64-linux-gnu-ld: $WORK/b058/_x011.o: relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: $WORK/b058/_x012.o: relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: $WORK/b058/_x013.o: relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Process exiting with code: 1

By the way, it's ok in MS Window.

**Comment by hrishikeshio** [comment]
Same problem. Anyone found a solution?

**Comment by dis2** [comment]
Deprecated. See README.md
